name: flutterquiz
description: A new Flutter application.
publish_to: "Renolation.Com"
version: 1.0.21+25

# Release Version: 2.1.8 (do not remove or edit this)
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.0
  connectivity_plus: ^6.0.3
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  encrypt: ^5.0.3
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_tex: ^4.0.6
  flutter_widget_from_html: ^0.14.11
  flutter_windowmanager: ^0.2.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  http: ^1.2.1
  iabtcf_consent_info: ^3.1.0
  image_cropper: ^5.0.1
  image_picker: ^1.1.0
  in_app_purchase: ^3.2.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  ios_insecure_screen_detector: ^0.0.2
  just_audio: ^0.9.37
  lottie: ^3.1.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  scratcher: ^2.5.0
  screenshot: ^2.4.0
  share_plus: any
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.0
  unity_ads_plugin: ^0.3.13
  url_launcher: ^6.2.6
  wakelock_plus: ^1.2.4


dependency_overrides:
  intl: ^0.18.1
  package_info_plus: ^7.0.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  dart_code_metrics_presets: ^2.11.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile/

    - assets/images/emojis/
    - assets/images/coins/

    - assets/languages/
    - assets/animations/

    - assets/sounds/
    - assets/files/
